### ISSUE TITLE
Demo on IngestAI

### ISSUE THREAD

**Issue by szotp-lc** [IngestAI/embedditor#58]
Hi. Readme says that embedditor should be available as demo on https://ingestai.io/ but I could not find it. Is it still available?

I tried running the app myself but I'm pretty inexperienced with docker and backend devolopment, and those instructions are not detailed enough.

**Comment by vladimirzhukov** [comment]
Yes, it's available on the IngestAI platform in the section "Other apps" -> "Custom Models" -> "Vector Storage".

**Comment by szotp-lc** [comment]
Found it, thanks!
